[calendar]
ids = [ "<your email>" ]

[token]
AccessToken = "<access token>"
RefreshToken = "<refresh token>"
TokenType = "Bearer"

[client]
ClientID = "<client id>"
ClientSecret = "<client secret>"
RedirectURL = "urn:ietf:wg:oauth:2.0:oob"
EndPoint = { TokenURL = "https://oauth2.googleapis.com/token", AuthURL = "https://accounts.google.com/o/oauth2/auth,token" }
Scopes = [
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/calendar.events.readonly"
]
